# Generated by Django 5.1.6 on 2025-02-06 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reel_code",
                    models.CharField(
                        help_text="Unique code for this reel",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "reel_type",
                    models.CharField(
                        choices=[("natural", "Natural"), ("golden", "Golden")],
                        help_text="Type of reel: Natural or Golden",
                        max_length=10,
                    ),
                ),
                (
                    "size_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Size in mm (e.g., 26.00 to 52.00)",
                        max_digits=5,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight of the reel in kg",
                        max_digits=10,
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Current stock available in kg",
                        max_digits=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight used in kg", max_digits=10
                    ),
                ),
                ("usage_date", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="inventory.reel",
                    ),
                ),
            ],
        ),
    ]
