# Generated by Django 5.1.6 on 2025-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='reel_code',
            field=models.CharField(help_text='Unique code for this reel', max_length=100),
        ),
        migrations.AlterField(
            model_name='reel',
            name='size_inch',
            field=models.DecimalField(decimal_places=2, help_text='Size in inch (e.g., 26.00 to 52.00)', max_digits=5),
        ),
    ]
