# Generated by Django 5.1.6 on 2025-02-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_reel_current_stock_alter_reel_reel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="reel_code",
            field=models.CharField(
                help_text="Unique code for this reel", max_length=100
            ),
        ),
    ]
