# Generated by Django 5.1.6 on 2025-02-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_reel_reel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="reel_code",
            field=models.CharField(help_text="Code for this reel", max_length=100),
        ),
    ]
