# Generated by Django 5.1.6 on 2025-02-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_reel_reel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Current stock available in kg",
                max_digits=10,
            ),
        ),
    ]
