# Generated by Django 5.1.6 on 2025-02-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_reel_current_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyusage",
            name="GSM",
            field=models.ForeignKey(
                default=120,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gsm_reels",
                to="inventory.reel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reel",
            name="reel_GSM",
            field=models.DecimalField(
                decimal_places=2,
                help_text="enter the GSM of paper ",
                max_digits=5,
                null=True,
            ),
        ),
    ]
