# Generated by Django 5.1.6 on 2025-02-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_dailyusage_gsm_reel_reel_gsm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reel",
            name="reel_GSM",
        ),
        migrations.CreateModel(
            name="ReelGSM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gsm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Enter the GSM of paper",
                        max_digits=5,
                    ),
                ),
                (
                    "reel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsm_values",
                        to="inventory.reel",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="dailyusage",
            name="GSM",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gsm_usages",
                to="inventory.reelgsm",
            ),
        ),
    ]
