# Generated by Django 5.1.6 on 2025-02-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_remove_reel_reel_gsm_reelgsm_alter_dailyusage_gsm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyusage",
            name="GSM",
        ),
        migrations.DeleteModel(
            name="ReelGSM",
        ),
    ]
