# Generated by Django 5.1.6 on 2025-03-31 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_remove_dailyusage_gsm_delete_reelgsm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyusage",
            options={"ordering": ["-usage_date"]},
        ),
        migrations.RemoveField(
            model_name="dailyusage",
            name="operator",
        ),
        migrations.AddField(
            model_name="dailyusage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dailyusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dailyusage",
            name="reel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.reel"
            ),
        ),
        migrations.AlterField(
            model_name="dailyusage",
            name="usage_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="dailyusage",
            name="used_weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
