# Generated by Django 5.1.6 on 2025-04-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0012_alter_dailyusage_options_remove_dailyusage_operator_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reel",
            options={"ordering": ["reel_code"]},
        ),
        migrations.AddField(
            model_name="reel",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reel",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reel",
            name="reel_code",
            field=models.CharField(
                help_text="Code for this reel", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="reel",
            name="reel_type",
            field=models.CharField(
                choices=[("natural", "Natural"), ("golden", "Golden")],
                help_text="Type of reel: Natural or Golden",
                max_length=20,
            ),
        ),
    ]
