# Generated by Django 5.1.6 on 2025-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0013_alter_reel_options_reel_created_at_reel_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reel",
            name="reel_code",
            field=models.CharField(help_text="Code for this reel", max_length=50),
        ),
    ]
